name: Build

on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'LICENSE-3RD-PARTY.txt'

jobs:
  build:
    name: Build the latest image
    runs-on: ubuntu-latest

    env:
      BUILDER: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: ci/build.sh

        
