name: Build

on: 
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish the latest version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: ci/build.sh

      - name: Publish image
        run: ci/publish.sh
        env:
          CR_USER: ${{ github.actor }}
          CR_PASS: ${{ secrets.GITHUB_TOKEN }}
          CR_REGISTRY: ghcr.io
        
